schema_version = "1.0.0"

id = "textured_voxelizer_mvp"
version = "0.5.0"
name = "Chromoxel"
tagline = "Texture-aware, symmetry-safe voxelization"
maintainer = "SKu11zZ"
type = "add-on"
website = "https://github.com/SKu11zZ/Chromoxel"

blender_version_min = "5.1.0"
license = ["SPDX:Apache-2.0"]
